FROM python:3.11.6
LABEL authors="TROCHON LOIC"

RUN pip install --upgrade pip
RUN pip install apache-beam
RUN pip install apache-beam[gcp]

RUN pip install google-cloud-storage

RUN pip install pandas